baseURL = "https://blog.glimesh.tv/"
languageCode = "en-us"
title = "Glimesh Blog"
theme="glimesh-theme"

# number of posts to show on home/category/tag pages (Default: 10)
paginate = 10
# number of words to use for summary on home/category/tag pages (Default: 70)
summaryLength = 50


[permalinks]
  posts = "/posts/:filename"
  page = "/:slug"

[[menu.sidebar]]
  name = "About Us"
  url = "https://glimesh.tv/about"

[[menu.sidebar]]
  name = "DMCA Policy"
  url = "https://glimesh.tv/about/dmca"

[[menu.sidebar]]
  name = "Frequently Asked Questions"
  url = "https://glimesh.tv/about/faq"

[[menu.sidebar]]
  name = "Open Data"
  url = "https://glimesh.tv/about/open-data"

[[menu.sidebar]]
  name = "Support"
  url = "https://support.glimesh.tv"

# Theme variables
#
[params]
  # Site author
  author = "Luke Strickland"

  # Description/subtitle for homepage (can be Markdown)
  # description = "A simple Hugo theme based on the Bootstrap v4 blog example."

  # Show header (default: true)
  #header_visible = true

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "The Glimesh blog"

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "glimesh"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]
  # Bulgarian date format is dd.mm.yyyy
  #date_format = "02.01.2006"

# vim: ts=2 sw=2 et